// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPxbZHC4ueLi1B61tvRnD4DP8_RCarO4c',
    appId: '1:403134134083:web:4730f4ced9fdf43dc561f6',
    messagingSenderId: '403134134083',
    projectId: 'monitor-me-app',
    authDomain: 'monitor-me-app.firebaseapp.com',
    storageBucket: 'monitor-me-app.firebasestorage.app',
    measurementId: 'G-V6WWLC01KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ_Zi2V-5xpEH4bpHGrl1vvFksxfAyX9I',
    appId: '1:403134134083:android:da08eba627243a4bc561f6',
    messagingSenderId: '403134134083',
    projectId: 'monitor-me-app',
    storageBucket: 'monitor-me-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArGOe7iq1hC1tD_RIKjF0HM4c9E58ml0k',
    appId: '1:403134134083:ios:b8abb6a21b31a660c561f6',
    messagingSenderId: '403134134083',
    projectId: 'monitor-me-app',
    storageBucket: 'monitor-me-app.firebasestorage.app',
    iosBundleId: 'com.son.monitorMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArGOe7iq1hC1tD_RIKjF0HM4c9E58ml0k',
    appId: '1:403134134083:ios:b8abb6a21b31a660c561f6',
    messagingSenderId: '403134134083',
    projectId: 'monitor-me-app',
    storageBucket: 'monitor-me-app.firebasestorage.app',
    iosBundleId: 'com.son.monitorMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPxbZHC4ueLi1B61tvRnD4DP8_RCarO4c',
    appId: '1:403134134083:web:11b614c939c5fd94c561f6',
    messagingSenderId: '403134134083',
    projectId: 'monitor-me-app',
    authDomain: 'monitor-me-app.firebaseapp.com',
    storageBucket: 'monitor-me-app.firebasestorage.app',
    measurementId: 'G-K14ES6Y18N',
  );
}
